[project]
name = "tx-crime"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
]
